import type { Prisma, PrismaClient } from "@prisma/client";

/**
 * The lessons that make the *whole* child journey walkable in development — one
 * per activity type, each with a quiz, narration, a video and a poster, so every
 * branch of the five-step player (`document/user-journey-manual.md` §4.3–4.5)
 * has content behind it. `seed.ts` already covers `drag_drop`; this file adds
 * `trace`, `match` and `puzzle`, and gives Ocean World the lessons it was
 * published without.
 *
 * Two different kinds of url appear below, and the difference is not cosmetic:
 *
 * - **`MediaAsset.url`** (mascots, video, posters, narration) is a plain column,
 *   so it takes a relative `/dev/...` path that Next serves straight out of
 *   `apps/web/public`. Generated by `apps/web/scripts/generate-dev-media.sh`.
 * - **Payload-embedded assets** (activity items, quiz options) go through
 *   `ImageAssetRefSchema`, which requires `https://` (`packages/types/src/primitives.ts`)
 *   — a relative path does not parse. Those point at `placehold.co`, which is a
 *   real host, so the images render once the origin is listed in
 *   `MEDIA_ASSET_HOSTS`. Payload *audio* has no such free host: it stays on the
 *   unresolvable `cdn.kidlearn.test` and is silent until a real CDN is wired up.
 */

const PLACEHOLDER_CDN = "https://placehold.co";
/** Unresolvable on purpose — see this file's header. */
const ASSET_CDN = "https://cdn.kidlearn.test";

type LocalizedText = { en: string; bn: string };

function picture(
  text: string,
  colour: string,
  alt: LocalizedText,
): Prisma.InputJsonValue {
  return {
    kind: "image",
    url: `${PLACEHOLDER_CDN}/400x400/${colour}/FFFFFF/png?text=${encodeURIComponent(text)}`,
    alt,
  };
}

function voice(name: string): Prisma.InputJsonValue {
  return {
    en: { kind: "audio", url: `${ASSET_CDN}/audio/en/${name}.mp3` },
    bn: { kind: "audio", url: `${ASSET_CDN}/audio/bn/${name}.mp3` },
  };
}

/** Fixed ids keep a re-seed idempotent, as everywhere else in this directory. */
const id = (suffix: string): string => `00000000-0000-0000-0000-${suffix}`;

interface MediaFixture {
  id: string;
  url: string;
  kind: "image" | "audio" | "video";
  language?: "en" | "bn";
}

const MEDIA = {
  oceanMascot: {
    id: id("000000000501"),
    url: "/dev/mascot-ocean-dolphin.png",
    kind: "image",
  },
  tracePoster: {
    id: id("000000000510"),
    url: "/dev/trace-letter-a.en.jpg",
    kind: "image",
    language: "en",
  },
  traceIntroEn: {
    id: id("000000000511"),
    url: "/dev/trace-letter-a-intro.en.mp3",
    kind: "audio",
    language: "en",
  },
  traceIntroBn: {
    id: id("000000000512"),
    url: "/dev/trace-letter-a-intro.bn.mp3",
    kind: "audio",
    language: "bn",
  },
  dolphinPoster: {
    id: id("000000000520"),
    url: "/dev/meet-the-dolphin.en.jpg",
    kind: "image",
    language: "en",
  },
  dolphinIntroEn: {
    id: id("000000000521"),
    url: "/dev/meet-the-dolphin-intro.en.mp3",
    kind: "audio",
    language: "en",
  },
  dolphinIntroBn: {
    id: id("000000000522"),
    url: "/dev/meet-the-dolphin-intro.bn.mp3",
    kind: "audio",
    language: "bn",
  },
  fishPoster: {
    id: id("000000000530"),
    url: "/dev/count-the-fish.en.jpg",
    kind: "image",
    language: "en",
  },
  fishIntroEn: {
    id: id("000000000531"),
    url: "/dev/count-the-fish-intro.en.mp3",
    kind: "audio",
    language: "en",
  },
  fishIntroBn: {
    id: id("000000000532"),
    url: "/dev/count-the-fish-intro.bn.mp3",
    kind: "audio",
    language: "bn",
  },
} satisfies Record<string, MediaFixture>;

async function upsertAsset(
  prisma: PrismaClient,
  fixture: MediaFixture,
): Promise<string> {
  const data = {
    url: fixture.url,
    kind: fixture.kind,
    language: fixture.language ?? null,
  };
  const asset = await prisma.mediaAsset.upsert({
    where: { id: fixture.id },
    update: data,
    create: { id: fixture.id, ...data },
  });
  return asset.id;
}

// ---------------------------------------------------------------- activities

const TRACE_LETTER_A: Prisma.InputJsonValue = {
  schemaVersion: 1,
  type: "trace",
  instructionAudio: voice("trace-the-letter-a"),
  glyph: "A",
  pathData: "M 20 180 L 100 20 M 100 20 L 180 180 M 55 110 L 145 110",
  guideDots: [
    { x: 20, y: 180 },
    { x: 100, y: 20 },
    { x: 180, y: 180 },
    { x: 55, y: 110 },
    { x: 145, y: 110 },
  ],
  strokeOrder: [0, 1, 2],
  // Generous for a three-year-old finger: the trace step must not become a test.
  tolerance: 18,
};

const MATCH_COUNT_THE_FISH: Prisma.InputJsonValue = {
  schemaVersion: 1,
  type: "match",
  instructionAudio: voice("match-the-number"),
  leftSet: [
    {
      id: "one",
      label: { en: "1", bn: "১" },
      image: picture("1", "00838F", { en: "The number one", bn: "সংখ্যা এক" }),
    },
    {
      id: "two",
      label: { en: "2", bn: "২" },
      image: picture("2", "00838F", { en: "The number two", bn: "সংখ্যা দুই" }),
    },
    {
      id: "three",
      label: { en: "3", bn: "৩" },
      image: picture("3", "00838F", {
        en: "The number three",
        bn: "সংখ্যা তিন",
      }),
    },
  ],
  rightSet: [
    {
      id: "one-fish",
      label: { en: "One fish", bn: "একটি মাছ" },
      image: picture("1 fish", "FF7043", { en: "One fish", bn: "একটি মাছ" }),
    },
    {
      id: "two-fish",
      label: { en: "Two fish", bn: "দুটি মাছ" },
      image: picture("2 fish", "FFA726", { en: "Two fish", bn: "দুটি মাছ" }),
    },
    {
      id: "three-fish",
      label: { en: "Three fish", bn: "তিনটি মাছ" },
      image: picture("3 fish", "26C6DA", { en: "Three fish", bn: "তিনটি মাছ" }),
    },
  ],
  pairs: [
    { leftId: "one", rightId: "one-fish" },
    { leftId: "two", rightId: "two-fish" },
    { leftId: "three", rightId: "three-fish" },
  ],
};

const PUZZLE_DOLPHIN: Prisma.InputJsonValue = {
  schemaVersion: 1,
  type: "puzzle",
  instructionAudio: voice("build-the-dolphin"),
  image: picture("Dolphin", "0277BD", {
    en: "A dolphin",
    bn: "একটি ডলফিন",
  }),
  grid: { rows: 2, cols: 2 },
  slots: [
    { index: 0, row: 0, col: 0 },
    { index: 1, row: 0, col: 1 },
    { index: 2, row: 1, col: 0 },
    { index: 3, row: 1, col: 1 },
  ],
  // One corner is handed to the child, so a 2×2 is three moves rather than four
  // — the Nursery shape the schema's `prePlaced` exists for.
  prePlaced: [0],
};

// -------------------------------------------------------------------- quizzes

interface QuestionFixture {
  id: string;
  format: "mcq" | "picture_select" | "match_pair" | "drag_answer";
  definition: Prisma.InputJsonValue;
}

interface QuizFixture {
  id: string;
  title: string;
  questions: QuestionFixture[];
}

const TRACE_QUIZ: QuizFixture = {
  id: id("000000000710"),
  title: "Letter A Tracing Quiz",
  questions: [
    {
      id: id("000000000711"),
      format: "mcq",
      definition: {
        schemaVersion: 1,
        type: "mcq",
        prompt: { en: "Which letter did we trace?", bn: "আমরা কোন বর্ণ আঁকলাম?" },
        promptAudio: voice("which-letter-did-we-trace"),
        options: [
          { id: "a", text: { en: "A", bn: "A" } },
          { id: "b", text: { en: "B", bn: "B" } },
          { id: "c", text: { en: "C", bn: "C" } },
        ],
        correctOptionId: "a",
      },
    },
    {
      id: id("000000000712"),
      format: "picture_select",
      definition: {
        schemaVersion: 1,
        type: "picture_select",
        prompt: {
          en: "Which one starts with A?",
          bn: "কোনটি A দিয়ে শুরু হয়?",
        },
        promptAudio: voice("which-one-starts-with-a"),
        options: [
          {
            id: "apple",
            text: { en: "Apple", bn: "আপেল" },
            image: picture("Apple", "E53935", {
              en: "A red apple",
              bn: "একটি লাল আপেল",
            }),
          },
          {
            id: "ball",
            text: { en: "Ball", bn: "বল" },
            image: picture("Ball", "1E88E5", {
              en: "A blue ball",
              bn: "একটি নীল বল",
            }),
          },
          {
            id: "cat",
            text: { en: "Cat", bn: "বিড়াল" },
            image: picture("Cat", "8D6E63", {
              en: "A cat",
              bn: "একটি বিড়াল",
            }),
          },
        ],
        correctOptionId: "apple",
      },
    },
    {
      id: id("000000000713"),
      format: "drag_answer",
      definition: {
        schemaVersion: 1,
        type: "drag_answer",
        prompt: { en: "Finish the word!", bn: "শব্দটি সম্পূর্ণ করো!" },
        promptAudio: voice("finish-the-word"),
        sentence: { en: "{blank}pple", bn: "{blank}pple" },
        options: [
          { id: "a", text: { en: "A", bn: "A" } },
          { id: "o", text: { en: "O", bn: "O" } },
          { id: "e", text: { en: "E", bn: "E" } },
        ],
        correctOptionId: "a",
      },
    },
  ],
};

const FISH_QUIZ: QuizFixture = {
  id: id("000000000720"),
  title: "Counting Fish Quiz",
  questions: [
    {
      id: id("000000000721"),
      format: "picture_select",
      definition: {
        schemaVersion: 1,
        type: "picture_select",
        prompt: { en: "Which shows three fish?", bn: "কোনটিতে তিনটি মাছ আছে?" },
        promptAudio: voice("which-shows-three-fish"),
        options: [
          {
            id: "one",
            text: { en: "One", bn: "এক" },
            image: picture("1 fish", "FF7043", {
              en: "One fish",
              bn: "একটি মাছ",
            }),
          },
          {
            id: "two",
            text: { en: "Two", bn: "দুই" },
            image: picture("2 fish", "FFA726", {
              en: "Two fish",
              bn: "দুটি মাছ",
            }),
          },
          {
            id: "three",
            text: { en: "Three", bn: "তিন" },
            image: picture("3 fish", "26C6DA", {
              en: "Three fish",
              bn: "তিনটি মাছ",
            }),
          },
        ],
        correctOptionId: "three",
      },
    },
    {
      id: id("000000000722"),
      format: "match_pair",
      definition: {
        schemaVersion: 1,
        type: "match_pair",
        prompt: {
          en: "Match the number to the fish!",
          bn: "সংখ্যার সাথে মাছ মেলাও!",
        },
        promptAudio: voice("match-the-number-to-the-fish"),
        leftColumn: [
          { id: "n1", text: { en: "1", bn: "১" } },
          { id: "n2", text: { en: "2", bn: "২" } },
        ],
        rightColumn: [
          {
            id: "f1",
            text: { en: "One fish", bn: "একটি মাছ" },
            image: picture("1 fish", "FF7043", {
              en: "One fish",
              bn: "একটি মাছ",
            }),
          },
          {
            id: "f2",
            text: { en: "Two fish", bn: "দুটি মাছ" },
            image: picture("2 fish", "FFA726", {
              en: "Two fish",
              bn: "দুটি মাছ",
            }),
          },
        ],
        correctPairs: [
          { leftId: "n1", rightId: "f1" },
          { leftId: "n2", rightId: "f2" },
        ],
      },
    },
    {
      id: id("000000000723"),
      format: "mcq",
      definition: {
        schemaVersion: 1,
        type: "mcq",
        prompt: { en: "What comes after two?", bn: "দুইয়ের পরে কী আসে?" },
        promptAudio: voice("what-comes-after-two"),
        options: [
          { id: "one", text: { en: "1", bn: "১" } },
          { id: "three", text: { en: "3", bn: "৩" } },
          { id: "five", text: { en: "5", bn: "৫" } },
        ],
        correctOptionId: "three",
      },
    },
  ],
};

const DOLPHIN_QUIZ: QuizFixture = {
  id: id("000000000730"),
  title: "Meet the Dolphin Quiz",
  questions: [
    {
      id: id("000000000731"),
      format: "mcq",
      definition: {
        schemaVersion: 1,
        type: "mcq",
        prompt: { en: "Where does a dolphin live?", bn: "ডলফিন কোথায় থাকে?" },
        promptAudio: voice("where-does-a-dolphin-live"),
        options: [
          { id: "ocean", text: { en: "In the ocean", bn: "সমুদ্রে" } },
          { id: "tree", text: { en: "In a tree", bn: "গাছে" } },
          { id: "desert", text: { en: "In the desert", bn: "মরুভূমিতে" } },
        ],
        correctOptionId: "ocean",
      },
    },
    {
      id: id("000000000732"),
      format: "picture_select",
      definition: {
        schemaVersion: 1,
        type: "picture_select",
        prompt: { en: "Which one is the dolphin?", bn: "কোনটি ডলফিন?" },
        promptAudio: voice("which-one-is-the-dolphin"),
        options: [
          {
            id: "dolphin",
            text: { en: "Dolphin", bn: "ডলফিন" },
            image: picture("Dolphin", "0277BD", {
              en: "A dolphin",
              bn: "একটি ডলফিন",
            }),
          },
          {
            id: "monkey",
            text: { en: "Monkey", bn: "বানর" },
            image: picture("Monkey", "8D6E63", {
              en: "A monkey",
              bn: "একটি বানর",
            }),
          },
          {
            id: "parrot",
            text: { en: "Parrot", bn: "টিয়া" },
            image: picture("Parrot", "43A047", {
              en: "A parrot",
              bn: "একটি টিয়া",
            }),
          },
        ],
        correctOptionId: "dolphin",
      },
    },
    {
      id: id("000000000733"),
      format: "mcq",
      definition: {
        schemaVersion: 1,
        type: "mcq",
        prompt: { en: "How does a dolphin move?", bn: "ডলফিন কীভাবে চলে?" },
        promptAudio: voice("how-does-a-dolphin-move"),
        options: [
          { id: "swims", text: { en: "It swims", bn: "সাঁতার কাটে" } },
          { id: "flies", text: { en: "It flies", bn: "ওড়ে" } },
          { id: "digs", text: { en: "It digs", bn: "গর্ত খোঁড়ে" } },
        ],
        correctOptionId: "swims",
      },
    },
  ],
};

/** The quiz `letter-a-practice` was published without (FR-LSN-04). */
const PRACTICE_QUIZ: QuizFixture = {
  id: id("000000000740"),
  title: "Practise the Letter A Quiz",
  questions: [
    {
      id: id("000000000741"),
      format: "mcq",
      definition: {
        schemaVersion: 1,
        type: "mcq",
        prompt: {
          en: "Which letter did we practise?",
          bn: "আমরা কোন বর্ণ অনুশীলন করলাম?",
        },
        promptAudio: voice("which-letter-did-we-practise"),
        options: [
          { id: "a", text: { en: "A", bn: "A" } },
          { id: "m", text: { en: "M", bn: "M" } },
          { id: "s", text: { en: "S", bn: "S" } },
        ],
        correctOptionId: "a",
      },
    },
    {
      id: id("000000000742"),
      format: "picture_select",
      definition: {
        schemaVersion: 1,
        type: "picture_select",
        prompt: { en: "Find the apple!", bn: "আপেলটি খুঁজে বের করো!" },
        promptAudio: voice("find-the-apple"),
        options: [
          {
            id: "apple",
            text: { en: "Apple", bn: "আপেল" },
            image: picture("Apple", "E53935", {
              en: "A red apple",
              bn: "একটি লাল আপেল",
            }),
          },
          {
            id: "duck",
            text: { en: "Duck", bn: "হাঁস" },
            image: picture("Duck", "FDD835", {
              en: "A duck",
              bn: "একটি হাঁস",
            }),
          },
          {
            id: "fish",
            text: { en: "Fish", bn: "মাছ" },
            image: picture("Fish", "26C6DA", {
              en: "A fish",
              bn: "একটি মাছ",
            }),
          },
        ],
        correctOptionId: "apple",
      },
    },
    {
      id: id("000000000743"),
      format: "mcq",
      definition: {
        schemaVersion: 1,
        type: "mcq",
        prompt: {
          en: "Ant starts with which letter?",
          bn: "Ant কোন বর্ণ দিয়ে শুরু?",
        },
        promptAudio: voice("ant-starts-with-which-letter"),
        options: [
          { id: "a", text: { en: "A", bn: "A" } },
          { id: "t", text: { en: "T", bn: "T" } },
          { id: "n", text: { en: "N", bn: "N" } },
        ],
        correctOptionId: "a",
      },
    },
  ],
};

async function upsertQuiz(
  prisma: PrismaClient,
  fixture: QuizFixture,
): Promise<string> {
  const quiz = await prisma.quiz.upsert({
    where: { id: fixture.id },
    update: { title: fixture.title, status: "published" },
    create: { id: fixture.id, title: fixture.title, status: "published" },
  });

  for (const [index, question] of fixture.questions.entries()) {
    const data = {
      quizId: quiz.id,
      format: question.format,
      sortOrder: index + 1,
      schemaVersion: 1,
      definition: question.definition,
    };
    await prisma.quizQuestion.upsert({
      where: { id: question.id },
      update: data,
      create: { id: question.id, ...data },
    });
  }
  return quiz.id;
}

// -------------------------------------------------------------------- lessons

interface LessonFixture {
  slug: string;
  title: string;
  sortOrder: number;
  worldSlug: "jungle" | "ocean";
  topicSlug: string;
  conceptsIntroduced: string[];
  activity: {
    id: string;
    type: "trace" | "match" | "puzzle";
    definition: Prisma.InputJsonValue;
  };
  quiz: QuizFixture;
  video: "en" | "both";
  poster: MediaFixture;
  intro: {
    en: { script: string; audio: MediaFixture };
    bn: { title: string; script: string; audio: MediaFixture };
  };
  titleTranslations: LocalizedText;
}

const LESSONS: LessonFixture[] = [
  {
    slug: "trace-letter-a",
    title: "Trace the Letter A",
    sortOrder: 4,
    worldSlug: "jungle",
    topicSlug: "alphabet",
    conceptsIntroduced: ["letter:A"],
    activity: {
      id: id("000000000120"),
      type: "trace",
      definition: TRACE_LETTER_A,
    },
    quiz: TRACE_QUIZ,
    video: "both",
    poster: MEDIA.tracePoster,
    intro: {
      en: {
        script:
          "Let's trace the letter A together! Follow the dots with your finger.",
        audio: MEDIA.traceIntroEn,
      },
      bn: {
        title: "A বর্ণ আঁকি",
        script: "চলো একসাথে A বর্ণটি আঁকি!",
        audio: MEDIA.traceIntroBn,
      },
    },
    titleTranslations: { en: "Trace the Letter A", bn: "A বর্ণ আঁকি" },
  },
  {
    slug: "count-the-fish",
    title: "Count the Fish",
    sortOrder: 1,
    worldSlug: "ocean",
    topicSlug: "ocean-life",
    conceptsIntroduced: ["number:1", "number:2", "number:3"],
    activity: {
      id: id("000000000121"),
      type: "match",
      definition: MATCH_COUNT_THE_FISH,
    },
    quiz: FISH_QUIZ,
    video: "en",
    poster: MEDIA.fishPoster,
    intro: {
      en: {
        script: "Let's count the fish in the reef. One, two, three!",
        audio: MEDIA.fishIntroEn,
      },
      bn: {
        title: "মাছ গুনি",
        script: "চলো প্রবালের মাছ গুনি। এক, দুই, তিন!",
        audio: MEDIA.fishIntroBn,
      },
    },
    titleTranslations: { en: "Count the Fish", bn: "মাছ গুনি" },
  },
  {
    slug: "meet-the-dolphin",
    title: "Meet the Dolphin",
    sortOrder: 2,
    worldSlug: "ocean",
    topicSlug: "ocean-life",
    conceptsIntroduced: ["animal:dolphin"],
    activity: {
      id: id("000000000122"),
      type: "puzzle",
      definition: PUZZLE_DOLPHIN,
    },
    quiz: DOLPHIN_QUIZ,
    video: "en",
    poster: MEDIA.dolphinPoster,
    intro: {
      en: {
        script:
          "Welcome to the ocean! Let's put the dolphin picture back together.",
        audio: MEDIA.dolphinIntroEn,
      },
      bn: {
        title: "ডলফিনের সাথে দেখা",
        script: "সমুদ্রে স্বাগতম! চলো ডলফিনের ছবিটা মিলাই।",
        audio: MEDIA.dolphinIntroBn,
      },
    },
    titleTranslations: { en: "Meet the Dolphin", bn: "ডলফিনের সাথে দেখা" },
  },
];

/**
 * Adds the activity-type coverage and the Ocean World lessons the child journey
 * needs. Runs after `seed.ts` has created the worlds, subjects and the English
 * `letter-a` video assets it reuses.
 */
export async function seedJourney(prisma: PrismaClient): Promise<void> {
  const worlds = new Map(
    (await prisma.world.findMany({ select: { id: true, slug: true } })).map(
      (world) => [world.slug, world.id],
    ),
  );
  const jungle = worlds.get("jungle");
  const ocean = worlds.get("ocean");
  if (jungle === undefined || ocean === undefined) {
    throw new Error("Worlds are missing — run `pnpm db:seed` first.");
  }

  // FR-WORLD-05: Ocean World was published without the mascot its card themes
  // itself with, which is why its home tile rendered empty.
  await prisma.world.update({
    where: { id: ocean },
    data: { mascotAssetId: await upsertAsset(prisma, MEDIA.oceanMascot) },
  });

  // Ocean World had no lessons at all, so tapping it opened an empty world. Its
  // topic hangs off `science`, which is published — `mathematics` is in draft,
  // and a draft subject hides every topic under it from the student query.
  const science = await prisma.subject.findUnique({
    where: { slug: "science" },
    select: { id: true },
  });
  if (science === null) {
    throw new Error("Subject `science` is missing — run `pnpm db:seed` first.");
  }

  const oceanLife = await prisma.topic.upsert({
    where: { subjectId_slug: { subjectId: science.id, slug: "ocean-life" } },
    update: { status: "published" },
    create: {
      slug: "ocean-life",
      name: "Ocean Life",
      sortOrder: 1,
      gradeLevels: ["NURSERY", "KG1"],
      status: "published",
      subjectId: science.id,
    },
  });

  for (const language of ["en", "bn"] as const) {
    await prisma.topicTranslation.upsert({
      where: { topicId_language: { topicId: oceanLife.id, language } },
      update: {},
      create: {
        topicId: oceanLife.id,
        language,
        name: language === "en" ? "Ocean Life" : "সমুদ্রের প্রাণী",
      },
    });
  }

  const topics = new Map<string, string>([["ocean-life", oceanLife.id]]);
  const alphabet = await prisma.topic.findFirst({
    where: { slug: "alphabet" },
    select: { id: true },
  });
  if (alphabet === null) {
    throw new Error("Topic `alphabet` is missing — run `pnpm db:seed` first.");
  }
  topics.set("alphabet", alphabet.id);

  // The films are `seed.ts`'s, reused rather than duplicated: one clip standing
  // in for every lesson is the honest shape of a placeholder library.
  const videoEn = id("000000000402");
  const videoBn = id("000000000403");

  for (const lesson of LESSONS) {
    const topicId = topics.get(lesson.topicSlug);
    if (topicId === undefined) continue;

    const [activityId, quizId, posterId, introEnId, introBnId] =
      await Promise.all([
        prisma.activity
          .upsert({
            where: { id: lesson.activity.id },
            update: {
              definition: lesson.activity.definition,
              status: "published",
            },
            create: {
              id: lesson.activity.id,
              type: lesson.activity.type,
              status: "published",
              schemaVersion: 1,
              definition: lesson.activity.definition,
            },
          })
          .then((activity) => activity.id),
        upsertQuiz(prisma, lesson.quiz),
        upsertAsset(prisma, lesson.poster),
        upsertAsset(prisma, lesson.intro.en.audio),
        upsertAsset(prisma, lesson.intro.bn.audio),
      ]);

    const row = {
      title: lesson.title,
      sortOrder: lesson.sortOrder,
      gradeLevels: ["NURSERY", "KG1"] as const,
      status: "published" as const,
      worldId: lesson.worldSlug === "jungle" ? jungle : ocean,
      activityId,
      quizId,
      conceptsIntroduced: lesson.conceptsIntroduced,
    };

    const created = await prisma.lesson.upsert({
      where: { topicId_slug: { topicId, slug: lesson.slug } },
      update: { ...row, gradeLevels: [...row.gradeLevels] },
      create: {
        slug: lesson.slug,
        topicId,
        ...row,
        gradeLevels: [...row.gradeLevels],
      },
    });

    const en = {
      title: lesson.titleTranslations.en,
      introScript: lesson.intro.en.script,
      introAudioAssetId: introEnId,
      videoAssetId: videoEn,
      videoPosterAssetId: posterId,
    };
    await prisma.lessonTranslation.upsert({
      where: { lessonId_language: { lessonId: created.id, language: "en" } },
      update: en,
      create: { lessonId: created.id, language: "en", ...en },
    });

    const bn = {
      title: lesson.intro.bn.title,
      introScript: lesson.intro.bn.script,
      introAudioAssetId: introBnId,
      videoAssetId: lesson.video === "both" ? videoBn : videoEn,
      // No Bangla poster anywhere: the English still is the `assetFallbacks`
      // path file 17 reports (FR-I18N-01), and it is worth keeping exercised.
      videoPosterAssetId: posterId,
    };
    await prisma.lessonTranslation.upsert({
      where: { lessonId_language: { lessonId: created.id, language: "bn" } },
      update: bn,
      create: { lessonId: created.id, language: "bn", ...bn },
    });
  }

  // `letter-a-practice` is published with an activity but no quiz, which drops a
  // child from step 3 straight to the reward — four steps, not the five every
  // other lesson has.
  const practice = await prisma.lesson.findFirst({
    where: { slug: "letter-a-practice" },
    select: { id: true, quizId: true },
  });
  if (practice !== null && practice.quizId === null) {
    await prisma.lesson.update({
      where: { id: practice.id },
      data: { quizId: await upsertQuiz(prisma, PRACTICE_QUIZ) },
    });
  }

  console.log(`Seeded ${LESSONS.length} journey lessons + the practice quiz.`);
}
