import { z } from "zod";
import { IsoDateTimeSchema, ok } from "./envelope.js";

/**
 * `/api/children/{id}/reports` and `/api/admin/jobs/weekly-reports` — the weekly
 * progress report (FR-DASH-05..06).
 *
 * Deviation from the implementation spec, which put these in
 * `packages/types/src/reports.ts`: the non-`api/` files in this package hold
 * vocabulary *both halves of the wire* share — a request enum the client validates
 * against as well. Neither endpoint here has a request body, so everything is
 * response-only and belongs in `api/` (`backend.md §7`). This is the same call
 * `api/dashboard.ts` records for file 29.
 */

/**
 * Which encouraging note a week earned (FR-DASH-05).
 *
 * A **key**, not a sentence, and that is the whole design. The server picks the
 * rule; the client renders `t(\`reports.notes.${noteKey}\`, noteParams)`, so the
 * note is Bangla for a Bangla-reading parent without the server knowing a
 * language it has no column for (see `LocalizedLabelSchema` in `api/dashboard.ts`
 * for why the parent's language never reaches the API).
 *
 * The order of this array is not the rule order — `selectNote` in
 * `apps/server/src/services/weeklyReportService.ts` owns that, and it is the one
 * place it is stated.
 *
 * Post-MVP: the note may be generated by the Claude API instead of a template.
 * That swap is behind `selectNote` and needs no change here — a generated note
 * still arrives as a key plus params, with the sentence itself in the locale files
 * or, if it is truly per-child prose, in the `note` column beside it.
 */
export const REPORT_NOTE_KEYS = [
  /** No activity at all — the one note that must not congratulate. */
  "quietWeek",
  /** Seven active days out of seven. */
  "perfectWeek",
  /** High first-attempt accuracy over enough questions to mean something. */
  "quizStar",
  /** Five or more active days. */
  "strongWeek",
  /** Five or more stories finished. */
  "bookworm",
  /** At least one lesson finished. */
  "steadyProgress",
  /** At least one story finished, but no lesson — so nothing above matched. */
  "storyTime",
  /** The fallback: something happened, but nothing was finished. */
  "gentleNudge",
] as const;

export const ReportNoteKeySchema = z.enum(REPORT_NOTE_KEYS);
export type ReportNoteKey = z.infer<typeof ReportNoteKeySchema>;

/**
 * One badge earned inside the week.
 *
 * `slug` and `name` rather than an id: the report is a snapshot a parent may read
 * months later, and nothing on this screen links anywhere, so an id would be a
 * field no client could use. The name is the admin label — `Badge` has no
 * translation table yet (see `mergeActivity` in `dashboardService.ts`).
 */
export const WeeklyReportBadgeSchema = z
  .object({ slug: z.string(), name: z.string() })
  .strict();

export type WeeklyReportBadge = z.infer<typeof WeeklyReportBadgeSchema>;

/**
 * Everything FR-DASH-05 asks a week to report, as stored in `WeeklyReport.metrics`.
 *
 * Persisted rather than derived on read, which is deliberate: a report is a record
 * of a week that has ended, and content unpublished in October must not silently
 * change August's figures. Re-running generation for the same week replaces the
 * row, so a late-arriving event is still counted (`generateWeeklyReport`).
 *
 * `quizAccuracy` is `null`, never `0`, for a week with no quiz answers. Zero
 * percent is a real and bad score; "no questions answered" is not a score at all,
 * and a client that cannot tell them apart tells a parent their child got
 * everything wrong.
 *
 * The three concept arrays are **sorted and deduped**, and they count what was met
 * for the first time this week — a letter revisited in a later lesson is not new
 * again.
 */
export const WeeklyReportMetricsSchema = z
  .object({
    /** Distinct local calendar days with at least one recorded event, 0–7. */
    activeDays: z.number().int().min(0).max(7),
    /** From the same density rule the dashboard and screen-time limit use. */
    learningMinutes: z.number().int().min(0),
    newLetters: z.array(z.string()),
    newWords: z.array(z.string()),
    newNumbers: z.array(z.string()),
    lessonsCompleted: z.number().int().min(0),
    storiesCompleted: z.number().int().min(0),
    /** First-attempt accuracy as a whole percent; `null` when nothing was answered. */
    quizAccuracy: z.number().int().min(0).max(100).nullable(),
    /**
     * How many distinct questions the accuracy above is an average of.
     *
     * Addition to the shape the implementation spec sketched, and the reason is
     * `selectNote`: its `quizStar` rule needs "≥90% over at least ten first
     * attempts", so without this the rule could not be a pure function of the
     * metrics — it would need a second argument, and a note could then never be
     * re-derived from a stored row. It also earns its place on screen: "12 of 14
     * right first time" is a figure a parent can act on, where 86% alone is not.
     *
     * `quizFirstAttempts === 0` is the same condition as `quizAccuracy === null`.
     * The redundancy is deliberate — a client rendering "x of y" needs the
     * denominator whether or not it also branches on the null.
     */
    quizFirstAttempts: z.number().int().min(0),
    /**
     * How many of those first attempts were right.
     *
     * Stored rather than left to the client to reconstruct from `quizAccuracy`,
     * because that reconstruction is lossy: the accuracy is rounded to a whole
     * percent, so 50 correct of 101 comes back as `Math.round(50 * 101 / 100)` —
     * 51, a number that never happened, printed beside the 101 that did.
     */
    quizFirstAttemptsCorrect: z.number().int().min(0),
    badgesEarned: z.array(WeeklyReportBadgeSchema),
    noteKey: ReportNoteKeySchema,
    /**
     * Interpolation values for the note's template — e.g. `{ activeDays: 7 }`.
     *
     * Loosely typed on purpose. Which params a note carries is a property of the
     * rule that produced it, and pinning a shape per key here would mean a second
     * source of truth beside the locale files that render them.
     */
    noteParams: z.record(z.union([z.string(), z.number()])),
  })
  .strict();

export type WeeklyReportMetrics = z.infer<typeof WeeklyReportMetricsSchema>;

/**
 * One week's report as the parent screen reads it.
 *
 * `weekStart` and `weekEnd` are both sent, and `weekEnd` is **inclusive** — the
 * Sunday, not the following Monday. The column stores only the Monday, but the
 * screen renders a range header ("17–23 Aug"), and a client computing the other
 * edge would be re-deriving a week length the server already decided.
 *
 * Both are full ISO timestamps even though `WeeklyReport.weekStart` is a
 * `@db.Date`: Prisma round-trips a date column as a `Date` at UTC midnight and
 * `res.json()` serialises that in full (`backend.md §7` — the wire format, never
 * the TypeScript type).
 *
 * `note` is the rendered **English** sentence, stored alongside the key. It is a
 * fallback and a debugging aid — a client with the locale files renders from
 * `metrics.noteKey` and ignores this. Nullable because the column is.
 */
export const WeeklyReportSchema = z
  .object({
    weekStart: IsoDateTimeSchema,
    /** The Sunday of the same week, inclusive. */
    weekEnd: IsoDateTimeSchema,
    metrics: WeeklyReportMetricsSchema,
    note: z.string().nullable(),
    createdAt: IsoDateTimeSchema,
  })
  .strict();

export type WeeklyReport = z.infer<typeof WeeklyReportSchema>;

/** Newest week first, so `reports[0]` is the card and the rest are the history. */
export const WeeklyReportListSchema = z
  .object({ reports: z.array(WeeklyReportSchema) })
  .strict();

export type WeeklyReportList = z.infer<typeof WeeklyReportListSchema>;

export const WeeklyReportListResponseSchema = ok(WeeklyReportListSchema);

/**
 * What the cron job answers (`POST /api/admin/jobs/weekly-reports`).
 *
 * `childrenProcessed` and the `weekStart` it generated, so an operator reading a
 * cron-job.org log can tell a successful no-op week from a run that saw no
 * children at all. Nothing per-child: the caller is a scheduler with no session
 * and no business knowing whose reports exist.
 */
export const WeeklyReportJobResultSchema = z
  .object({
    childrenProcessed: z.number().int().min(0),
    weekStart: IsoDateTimeSchema,
  })
  .strict();

export type WeeklyReportJobResult = z.infer<typeof WeeklyReportJobResultSchema>;

export const WeeklyReportJobResponseSchema = ok(WeeklyReportJobResultSchema);
