-- Supabase's Data API serves "public" to anyone holding the project's anon key, which is
-- public by design. RLS with no policies refuses every role but the owner; Prisma connects as
-- the owner, so the server is unaffected. ENABLE is a catalogue flag — no rows are scanned.

ALTER TABLE "AIGenerationJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Activity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ActivityTranslation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AdminUser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Badge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Character" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CharacterSheet" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChildCharacter" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChildProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Lesson" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LessonProgress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LessonTranslation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MediaAsset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Parent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Quiz" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QuizQuestion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QuizQuestionTranslation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QuizResponse" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RewardLedger" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ScreenTimeSetting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SessionEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Story" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StoryPage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StoryPageTranslation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StoryTranslation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Streak" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Subject" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SubjectTranslation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Topic" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TopicTranslation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WeeklyReport" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "World" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorldTranslation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "verification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
